module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'repo',
        'monorepo',
        'config',
        'lint',
        'format',
        'git',
        'docker',
        'infra',
        'k8s',
        'ci',
        'common',
        'kafka',
        'db',
        'observability',
        'gateway',
        'auth',
        'catalog',
        'inventory',
        'order',
        'payment',
        'notification',
        'docs',
        'deps',
      ],
    ],
  },
};
